### PR TITLE
v1.0.6

### PR DESCRIPTION
**Pull request by baudehlo**
Updates tld files

### CODE REVIEW

**Comment by baudehlo** [comment]
@msimerson I don't seem to have publish rights on npm for this...

**Comment by msimerson** [comment]
You need to be logged in as the 'haraka' npm user. I recall something about needing a $pay npm account so that more than one user can have publish permission. Quick fix: npm logout && npm login. I'll look again tomorrow ame see if there's a way to enable more user names to publish.

**Comment by msimerson** [comment]
Also, this is messed up and should not have been merged. Look at the diff for extra-tlds.

**Comment by baudehlo** [comment]
Yikes sorry about that. I guess the update script needs some love. Glad I couldn't publish!

**Comment by msimerson** [comment]
> Yikes sorry about that. I guess the update script needs some love. Glad I couldn't publish!

Right, the URL from extra-tld doesn't work any longer. I'll create an issue for this.

**Comment by msimerson** [comment]
I think I've also fixed the npm publish issue too:

````
$ npm owner add baudehlo
+ baudehlo (haraka-tld)
````

**Comment by msimerson** [comment]
Bah! I looked at Haraka package and did this:

````
~/Documents/git/haraka-tld $ npm owner add msergeant
+ msergeant (haraka-tld)
~/Documents/git/haraka-tld $ npm owner rm baudehlo
- baudehlo (haraka-tld)
````

**Pull request merged**
